apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: limit-endpoint-count
spec:
  validationFailureAction: enforce
  rules:
  - name: check-endpoint-count
    match:
      any:
      - resources:
          kinds:
          - CiliumNetworkPolicy
    validate:
      message: "Policy applies to too many endpoints; limit is 10."
      deny:
        conditions:
          all:
          - key: "{{ length(request.object.spec.endpointSelector.matchLabels) }}"
            operator: GreaterThan
            value: 10
